name: Build Website

on:
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Yarn
      run: npm install --global yarn && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Build website
      run: yarn build

    - name: Clone branch gh-pages
      uses: actions/checkout@v3
      with:
        path: 'gh-pages'
        ref: gh-pages

    - name: Move .git to build
      run: mv './gh-pages/.git' './build'

    - name: Push to pages
      continue-on-error: true
      run: |
        cd './build'
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update pages"
        git push
